---
name: Gradle Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Gradle Package

    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]"
    # or "github-actions[bot]".
    # Otherwise, clone it normally.
    if: |
        (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
        (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
        (github.event_name == 'pull_request_target' && github.actor == 'github-actions[bot]') ||
        (github.event_name != 'pull_request_target' && github.actor != 'github-actions[bot]')
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Checkout
      if: ${{ github.event_name == 'pull_request_target' }}
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version-file: .java-version
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3.4.1
      with:
        arguments: build

    - name: Publish to GitHub Packages
      uses: gradle/actions/setup-gradle@v3.4.1
      with:
        arguments: publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
