---
name: Gradle build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Gradle build

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Set up JDK 11
      uses: actions/setup-java@v3.4.1
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.2.3
      with:
        arguments: build
