---
name: Gradle Package

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    name: Gradle Package

    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Set up JDK 11
      uses: actions/setup-java@v3.4.1
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.0
      with:
        arguments: build

    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v2.3.0
      with:
        arguments: publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
