---
name: Lint Code Base

on:
  pull_request:

jobs:
  build:
    name: Lint Code Base

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.9.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_KOTLIN_ANDROID: false
